import type { Metadata } from "next";
import {
  DynaPuff,
  Geist,
  Geist_Mono,
  Manrope,
  Vazirmatn,
} from "next/font/google";
import "./globals.css";

const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});
const vazirmatn = Vazirmatn({
  variable: "--font-vazir-matn",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${vazirmatn.variable} ${manrope.variable} h-full antialiased manrope`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
