import type { Metadata } from "next";
import { DynaPuff, Geist, Geist_Mono, Vazirmatn } from "next/font/google";
import "./globals.css";

const dynaPuff = DynaPuff({
  variable: "--font-dyna-puff",
  subsets: ["latin"],
  weight: ["400", "500", "700"],
});
const vazirmatn = Vazirmatn({
  variable: "--font-vazir-matn",
  subsets: ["latin", "arabic"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="fa"
      className={`${vazirmatn.variable} ${dynaPuff.variable} h-full antialiased vazir-matn`}
      dir="rtl"
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
